### ISSUE TITLE
元素水平垂直居中

### ISSUE THREAD

**Issue by joneqing** [joneqing/joneqing-article#2]
* absolute + 负margin

```html
<div class='parent'>
  <div class='child'>child</div>
</div>
```

```css
.parent {
  width: 300px;
  height: 300px;
  position: relative;
}
.child {
  width: 100px;
  height: 100px;
  position: absolute;
  top: 50%;
  left: 50%;
  margin-top: -50px;
  margin-left: -50px;
}
```

* flex

```html
<div class='parent'>
  <div class='child'>child</div>
</div>
```

```css
.parent {
  width: 300px;
  height: 300px;
  display: flex;
  justify-content: center;
  align-items: center;
}
.child {
  width: 100px;
  height: 100px;
}
```

* table
1. 第一种

```html
<div class='parent'>
  <div class='child'>child</div>
</div>
```

```css
.parent {
  width: 100px;
  height: 100px;
  display: table-cell;
  vertical-align: middle;
}
.child {
  width: 100px;
  height: 100px;
  margin: 0 auto;
}
```

2. 第二种

```html
<table>
  <tbody>
    <tr>
      <td class='parent'>
        <div class='child'>child</div>
      </td>
    </tr>
  </tbody>
</table>
```

```css
.parent {
  width: 300px;
  height: 300px;
  text-align: center;
}
.child {
  width: 100px;
  height: 100px;
  display: inline-block;
}
```
